python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 2
python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 3
python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 4
python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 5
python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 6
python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 7
python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 8
python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 9
python3 main_n_cls.py --train --test --epochs 200 --net SimpleDLA --num_class 10

python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 2
python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 3
python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 4
python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 5
python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 6
python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 7
python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 8
python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 9
python3 main_n_cls.py --train --test --epochs 200 --net VGG19 --num_class 10

python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 2
python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 3
python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 4
python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 5
python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 6
python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 7
python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 8
python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 9
python3 main_n_cls.py --train --test --epochs 200 --net ResNet18 --num_class 10
